// src/lib/components/Nav.svelte
<header class="attv-header">
  <h1 class="logo">
    <a href="/">ATTV'71</a>
  </h1>
  <nav class="main-nav">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/evenementen">Evenementen</a></li>
      <li><a href="/over-ons">Over ons</a></li>
      <li><a href="/competitie">Competitie</a></li>
      <li><a href="/contact">Contact</a></li>
    </ul>
  </nav>
</header>

<style>
  .attv-header {
    display: grid;
    grid-template-areas: ". logo nav-links";
    grid-template-columns: 9% 49% 1fr;
    align-items: center;

    min-height: 15vh;
  }

  a {
    font-size: 1.2rem;
    text-decoration: none;
    color: var(--attv-black);
  }

  header {
    background-color: var(--attv-yellow);
  }

  h1 {
    font-size: 1.5rem;
  }

  ul {
    display: flex;
    gap: 1.5rem;

    list-style: none;
  }

  .logo {
    grid-area: logo
  }

  .main-nav {
    grid-area: nav-links
  }
</style>

// app2/components/Nav.vue
<script setup lang="ts">
interface NavigationItem {
  text: string
  href: string
  children?: {
    text: string
    href: string
  }[]
}

const nav: NavigationItem[] = [
  {
    text: 'Sample1',
    href: '/',
  },
  {
    text: 'Sample2',
    href: '/sample2',
  },
  {
    text: 'Sample3',
    href: '/sample3',
    children: [
      {
        text: 'Sample3',
        href: '/sample3',
      },
      {
        text: 'Sample4',
        href: '/sample4',
      },
      {
        text: 'Sample5',
        href: '/sample5',
      },
    ],
  },
]
</script>

<template>
  <nav>
    <ul :class="$style['nav-list']">
      <template v-for="navItem in nav" :key="navItem.text">
        <NavItem v-if="!navItem.children" :href="navItem.href">{{ navItem.text }}</NavItem>
        <NavDropdown v-else :href="navItem.href" :children="navItem.children">{{ navItem.text }}</NavDropdown>
      </template>
    </ul>
  </nav>
</template>

<style lang="postcss" module>
.nav-list {
  display: flex;
  gap: 1.5rem;
  font-size: 1.25rem;
  list-style: none;
  color: black;
}
</style>
